-- P01: schema-qualified jobs row and primitive claim verbs.
-- Replay-safe. No GRANT, extensions, public objects, or transaction control.

CREATE TABLE IF NOT EXISTS cordis.jobs (
    job_id bigint GENERATED BY DEFAULT AS IDENTITY,
    run_id text NOT NULL,
    job_type text NOT NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'PENDING',
    priority integer NOT NULL DEFAULT 0,
    attempt integer NOT NULL DEFAULT 1,
    available_at timestamptz NOT NULL DEFAULT '-infinity'::timestamptz,
    claim_token uuid,
    claimed_by text,
    claim_expires_at timestamptz,
    result jsonb,
    error jsonb,
    created_at timestamptz NOT NULL DEFAULT pg_catalog.clock_timestamp(),
    completed_at timestamptz,
    CONSTRAINT jobs_pkey PRIMARY KEY (job_id),
    CONSTRAINT jobs_run_id_key UNIQUE (run_id),
    CONSTRAINT jobs_claim_token_key UNIQUE (claim_token),
    CONSTRAINT jobs_status_check CHECK (
        status IN ('PENDING', 'RUNNING', 'WAITING', 'SLEEPING', 'DONE', 'ERROR')
    ),
    CONSTRAINT jobs_attempt_check CHECK (attempt >= 1),
    CONSTRAINT jobs_claim_fields_check CHECK (
        (
            status = 'RUNNING'
            AND claim_token IS NOT NULL
            AND claimed_by IS NOT NULL
            AND claim_expires_at IS NOT NULL
        )
        OR (
            status <> 'RUNNING'
            AND claim_token IS NULL
            AND claimed_by IS NULL
            AND claim_expires_at IS NULL
        )
    ),
    CONSTRAINT jobs_claimed_by_nonblank_check CHECK (
        claimed_by IS NULL OR pg_catalog.btrim(claimed_by) <> ''
    ),
    CONSTRAINT jobs_terminal_time_check CHECK (
        (
            status IN ('DONE', 'ERROR')
            AND completed_at IS NOT NULL
        )
        OR (
            status NOT IN ('DONE', 'ERROR')
            AND completed_at IS NULL
        )
    )
);

CREATE INDEX IF NOT EXISTS jobs_ready_idx
    ON cordis.jobs (priority DESC, available_at ASC, job_id ASC)
    WHERE status = 'PENDING';

CREATE INDEX IF NOT EXISTS jobs_stale_claim_idx
    ON cordis.jobs (claim_expires_at ASC, job_id ASC)
    WHERE status = 'RUNNING';

CREATE OR REPLACE FUNCTION cordis.release_stale(
    p_run_id text DEFAULT NULL,
    p_limit integer DEFAULT 100
)
RETURNS integer
LANGUAGE plpgsql
VOLATILE
SECURITY INVOKER
SET search_path TO pg_catalog
AS $fn$
DECLARE
    t0 timestamptz;
    n integer;
BEGIN
    IF p_limit IS NULL OR p_limit <= 0 THEN
        RAISE EXCEPTION 'p_limit must be positive'
            USING ERRCODE = 'invalid_parameter_value';
    END IF;
    IF p_run_id IS NOT NULL AND pg_catalog.btrim(p_run_id) = '' THEN
        RAISE EXCEPTION 'p_run_id must not be blank'
            USING ERRCODE = 'invalid_parameter_value';
    END IF;

    t0 := pg_catalog.clock_timestamp();

    WITH candidates AS (
        SELECT job_id
          FROM cordis.jobs
         WHERE status = 'RUNNING'
           AND claim_expires_at <= t0
           AND (p_run_id IS NULL OR run_id = p_run_id)
         ORDER BY claim_expires_at ASC, job_id ASC
         FOR UPDATE SKIP LOCKED
         LIMIT p_limit
    )
    UPDATE cordis.jobs AS j
       SET status = 'PENDING',
           available_at = t0,
           attempt = j.attempt + 1,
           claim_token = NULL,
           claimed_by = NULL,
           claim_expires_at = NULL,
           completed_at = NULL,
           result = NULL,
           error = NULL
      FROM candidates AS c
     WHERE j.job_id = c.job_id;

    GET DIAGNOSTICS n = ROW_COUNT;
    RETURN n;
END;
$fn$;

CREATE OR REPLACE FUNCTION cordis.claim_job(
    p_run_id text,
    p_worker_id text,
    p_lease_seconds integer DEFAULT 90
)
RETURNS SETOF cordis.jobs
LANGUAGE plpgsql
VOLATILE
SECURITY INVOKER
SET search_path TO pg_catalog
AS $fn$
DECLARE
    t_claim timestamptz;
BEGIN
    IF p_worker_id IS NULL OR pg_catalog.btrim(p_worker_id) = '' THEN
        RAISE EXCEPTION 'p_worker_id must not be blank'
            USING ERRCODE = 'invalid_parameter_value';
    END IF;
    IF p_run_id IS NOT NULL AND pg_catalog.btrim(p_run_id) = '' THEN
        RAISE EXCEPTION 'p_run_id must not be blank'
            USING ERRCODE = 'invalid_parameter_value';
    END IF;
    IF p_lease_seconds IS NULL OR p_lease_seconds <= 0 THEN
        RAISE EXCEPTION 'p_lease_seconds must be positive'
            USING ERRCODE = 'invalid_parameter_value';
    END IF;

    PERFORM cordis.release_stale(p_run_id, 100);
    t_claim := pg_catalog.clock_timestamp();

    RETURN QUERY
    WITH picked AS (
        SELECT job_id
          FROM cordis.jobs
         WHERE status = 'PENDING'
           AND available_at <= t_claim
           AND (p_run_id IS NULL OR run_id = p_run_id)
         ORDER BY priority DESC, available_at ASC, job_id ASC
         FOR UPDATE SKIP LOCKED
         LIMIT 1
    )
    UPDATE cordis.jobs AS j
       SET status = 'RUNNING',
           claim_token = pg_catalog.gen_random_uuid(),
           claimed_by = p_worker_id,
           claim_expires_at = t_claim + pg_catalog.make_interval(secs => p_lease_seconds),
           completed_at = NULL,
           result = NULL,
           error = NULL
      FROM picked
     WHERE j.job_id = picked.job_id
     RETURNING j.*;
END;
$fn$;

CREATE OR REPLACE FUNCTION cordis.renew_claim(
    p_claim_token uuid,
    p_extend_seconds integer DEFAULT 90
)
RETURNS boolean
LANGUAGE plpgsql
VOLATILE
SECURITY INVOKER
SET search_path TO pg_catalog
AS $fn$
BEGIN
    IF p_extend_seconds IS NULL OR p_extend_seconds <= 0 THEN
        RAISE EXCEPTION 'p_extend_seconds must be positive'
            USING ERRCODE = 'invalid_parameter_value';
    END IF;

    UPDATE cordis.jobs
       SET claim_expires_at = pg_catalog.clock_timestamp() + pg_catalog.make_interval(secs => p_extend_seconds)
     WHERE claim_token = p_claim_token
       AND status = 'RUNNING'
       AND claim_expires_at > pg_catalog.clock_timestamp();

    RETURN FOUND;
END;
$fn$;

CREATE OR REPLACE FUNCTION cordis.yield_claim(
    p_claim_token uuid
)
RETURNS boolean
LANGUAGE plpgsql
VOLATILE
SECURITY INVOKER
SET search_path TO pg_catalog
AS $fn$
BEGIN
    UPDATE cordis.jobs
       SET status = 'PENDING',
           available_at = pg_catalog.clock_timestamp(),
           claim_token = NULL,
           claimed_by = NULL,
           claim_expires_at = NULL,
           completed_at = NULL,
           result = NULL,
           error = NULL
     WHERE claim_token = p_claim_token
       AND status = 'RUNNING'
       AND claim_expires_at > pg_catalog.clock_timestamp();

    RETURN FOUND;
END;
$fn$;

CREATE OR REPLACE FUNCTION cordis.complete_claim(
    p_claim_token uuid,
    p_result jsonb DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
VOLATILE
SECURITY INVOKER
SET search_path TO pg_catalog
AS $fn$
BEGIN
    UPDATE cordis.jobs
       SET status = 'DONE',
           result = p_result,
           error = NULL,
           completed_at = pg_catalog.clock_timestamp(),
           claim_token = NULL,
           claimed_by = NULL,
           claim_expires_at = NULL
     WHERE claim_token = p_claim_token
       AND status = 'RUNNING'
       AND claim_expires_at > pg_catalog.clock_timestamp();

    RETURN FOUND;
END;
$fn$;

CREATE OR REPLACE FUNCTION cordis.fail_claim(
    p_claim_token uuid,
    p_reason jsonb
)
RETURNS boolean
LANGUAGE plpgsql
VOLATILE
SECURITY INVOKER
SET search_path TO pg_catalog
AS $fn$
BEGIN
    IF p_reason IS NULL THEN
        RAISE EXCEPTION 'p_reason must not be null'
            USING ERRCODE = 'invalid_parameter_value';
    END IF;

    UPDATE cordis.jobs
       SET status = 'ERROR',
           error = p_reason,
           result = NULL,
           completed_at = pg_catalog.clock_timestamp(),
           claim_token = NULL,
           claimed_by = NULL,
           claim_expires_at = NULL
     WHERE claim_token = p_claim_token
       AND status = 'RUNNING'
       AND claim_expires_at > pg_catalog.clock_timestamp();

    RETURN FOUND;
END;
$fn$;

CREATE OR REPLACE FUNCTION cordis.get_schema_version()
RETURNS text
LANGUAGE sql
IMMUTABLE
SECURITY INVOKER
AS $$
  SELECT 'p01'::text;
$$;
